name: Release Homebrew Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "TARGET_ARCH=arm64" >> $GITHUB_ENV
          else
            echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
          fi

      - name: Set Version
        run: |
          VERSION=${GITHUB_REF##refs/tags/}
          VERSION_NO_V=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_NO_V=$VERSION_NO_V" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew install gmp bazelisk
          pip3 install cpplint pytest numpy sympy==1.12.1 cairo-lang==0.12.0

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Test
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Rename binaries for Homebrew
        run: |
          mv /usr/local/bin/cpu_air_prover ./cpu_air_prover-${TARGET_ARCH}
          mv /usr/local/bin/cpu_air_verifier ./cpu_air_verifier-${TARGET_ARCH}

      - name: Package binaries
        run: |
          tar -czvf stone-prover-${VERSION_NO_V}-macos-${TARGET_ARCH}.tar.gz cpu_air_prover-${TARGET_ARCH} cpu_air_verifier-${TARGET_ARCH}

      - name: Compute SHA256
        id: compute_sha
        run: |
          SHA256=$(shasum -a 256 stone-prover-${VERSION_NO_V}-macos-${TARGET_ARCH}.tar.gz | awk '{ print $1 }')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: stone-prover-${VERSION_NO_V}-macos-${TARGET_ARCH}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        env:
          SHA256: ${{ steps.compute_sha.outputs.sha256 }}
          VERSION_NO_V: ${{ env.VERSION_NO_V }}
          TARGET_ARCH: ${{ env.TARGET_ARCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/MrRoudyk/homebrew-stone-prover.git
          cd homebrew-stone-prover

          sed -i '' "s|url \".*\"|url \"https://github.com/MrRoudyk/stone-packaging/releases/download/v${VERSION_NO_V}/stone-prover-${VERSION_NO_V}-macos-${TARGET_ARCH}.tar.gz\"|" Formula/stone-prover.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/stone-prover.rb

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/stone-prover.rb
          git commit -m "Update Stone Prover to version ${VERSION_NO_V}" || echo "No changes to commit"
          git push origin main
