name: Release Homebrew Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    runs-on: macos-latest
    name: Build on ${{ matrix.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "TARGET_ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "TARGET_ARCH: $TARGET_ARCH"

      - name: Set Version
        run: |
          VERSION=${GITHUB_REF##refs/tags/}
          VERSION_NO_V=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_NO_V=$VERSION_NO_V" >> $GITHUB_ENV
          echo "VERSION: $VERSION"
          echo "VERSION_NO_V: $VERSION_NO_V"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          brew install gmp bazelisk
          pip3 install cpplint pytest numpy sympy==1.12.1 cairo-lang==0.12.0

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Test
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Copy and rename binaries for Homebrew
        run: |
          cp /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_prover ./cpu_air_prover-${{ env.TARGET_ARCH }}
          cp /tmp/stone-prover/build/bazelbin/src/starkware/main/cpu/cpu_air_verifier ./cpu_air_verifier-${{ env.TARGET_ARCH }}
          echo "Copied and renamed binaries."

      - name: Make binaries executable
        run: |
          chmod +x cpu_air_prover-${{ env.TARGET_ARCH }}
          chmod +x cpu_air_verifier-${{ env.TARGET_ARCH }}
          echo "Set executable permissions."

      - name: Verify binaries
        run: |
          echo "Verifying binaries:"
          ls -l cpu_air_prover-${{ env.TARGET_ARCH }}
          ls -l cpu_air_verifier-${{ env.TARGET_ARCH }}

      - name: Package binaries
        run: |
          tar -czvf stone-prover-${{ env.VERSION_NO_V }}-macos-${{ env.TARGET_ARCH }}.tar.gz cpu_air_prover-${{ env.TARGET_ARCH }} cpu_air_verifier-${{ env.TARGET_ARCH }}
          echo "Packaged binaries into stone-prover-${{ env.VERSION_NO_V }}-macos-${{ env.TARGET_ARCH }}.tar.gz"

      - name: Compute SHA256
        id: compute_sha
        run: |
          SHA256=$(shasum -a 256 stone-prover-${{ env.VERSION_NO_V }}-macos-${{ env.TARGET_ARCH }}.tar.gz | awk '{ print $1 }')
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          echo "Computed SHA256: $SHA256"

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: stone-prover-${{ env.VERSION_NO_V }}-macos-${{ env.TARGET_ARCH }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Homebrew Formula Repository
        uses: actions/checkout@v3
        with:
          repository: MrRoudyk/homebrew-stone-prover
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: homebrew-stone-prover

      - name: Update Homebrew Formula
        working-directory: homebrew-stone-prover
        run: |
          ARCH_SUFFIX=${{ env.TARGET_ARCH }}
          VERSION="${{ env.VERSION_NO_V }}"
          URL="https://github.com/MrRoudyk/stone-packaging/releases/download/v${VERSION}/stone-prover-${VERSION}-macos-${ARCH_SUFFIX}.tar.gz"
          SHA256="${{ steps.compute_sha.outputs.sha256 }}"

          sed -i '' "/^  bottle do$/,/^  end$/d" Formula/stone-prover.rb
          echo "  bottle do" >> Formula/stone-prover.rb
          echo "    root_url \"$URL\"" >> Formula/stone-prover.rb
          echo "    sha256 cellar: :any_skip_relocation, ${ARCH_SUFFIX}: \"$SHA256\"" >> Formula/stone-prover.rb
          echo "  end" >> Formula/stone-prover.rb

          sed -i '' "s|version \".*\"|version \"$VERSION\"|" Formula/stone-prover.rb

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/stone-prover.rb
          git commit -m "Update Stone Prover to version $VERSION for $ARCH_SUFFIX" || echo "No changes to commit"
          git push origin main
